Repository Code4GovTech/c4gt-milestones, pull requests merged in 2023-08, with the labels that each got.

#418 Week 4
  docs/2023/BeckN/BeckN Smart Policy Infrastructure/updates/2023-07-28.md
Labels: Changes requested

#402 week 4 updated
  docs/2023/TrustBot and POSHpal/POSHpal/updates/2023-07-21.md
  docs/2023/TrustBot and POSHpal/POSHpal/updates/2023-07-28.md
Labels: Changes requested

#344 Player2
  docs/2023/QuML/Enhanced Quml player for Enhanced Question types/updates/2023-07-28.md
  images/Screenshot 2023-07-28 204800.png
Labels: Changes requested

#423 Week 4 Updates
  docs/2023/DevOps Pipeline/Build v2 of devops pipeline/updates/2023-07-28.md
Labels: Changes requested

#263 Weekly updates for week 1,2,3,4 of Theming and configuration
  docs/2023/Sunbird UCI/Theming and configuration/_category_.json
  docs/2023/Sunbird UCI/Theming and configuration/index.md
  docs/2023/Sunbird UCI/Theming and configuration/setup.md
  docs/2023/Sunbird UCI/Theming and configuration/updates/2023-07-07.md
  docs/2023/Sunbird UCI/Theming and configuration/updates/2023-07-14.md
  docs/2023/Sunbird UCI/Theming and configuration/updates/2023-07-21.md
  docs/2023/Sunbird UCI/Theming and configuration/updates/2023-07-28.md
  docs/2023/Sunbird UCI/Theming and configuration/updates/2023-08-04.md
  docs/2023/Sunbird UCI/Theming and configuration/updates/2023-08-11.md
  docs/2023/Sunbird UCI/Theming and configuration/updates/2023-08-18.md
  docs/2023/Sunbird UCI/Theming and configuration/updates/2023-08-25.md
  docs/2023/Sunbird UCI/Theming and configuration/updates/2023-09-01.md
  docs/2023/Sunbird UCI/Theming and configuration/updates/_category_.json
Labels: Changes requested

#455 [feat] added week 5 report
  docs/2023/DIGIT/Vehicle Tracker/static/week5/img-1.jpg
  docs/2023/DIGIT/Vehicle Tracker/static/week5/img-2.jpg
  docs/2023/DIGIT/Vehicle Tracker/updates/2023-08-04.md
Labels: Changes requested

#461 CARE:Live Feed Camera Enhancement week 5 updates
  docs/2023/CARE/Live Camera Feed Enhancement/updates/2023-08-04.md
  docs/2023/CARE/Live Camera Feed Enhancement/updates/resources/add-preset-week5.png
  docs/2023/CARE/Live Camera Feed Enhancement/updates/resources/disable-bed.png
Labels: Changes requested

#410 added week 4 milestones
  docs/2023/DIGIT/Jurisdiction Based Workflow/updates/2023-07-28.md
  docs/2023/DIGIT/Jurisdiction Based Workflow/updates/2023-08-04.md
Labels: Changes requested

#483 Updates Week 5 : AI-Tools
  docs/2023/AI Tools/Deployment Optimization/updates/2023-08-04.md
  docs/2023/AI Tools/Deployment Optimization/updates/2023-08-11.md
Labels: Changes requested

#588 Week 6 Updates
  docs/2023/Sunbird RC/Credential Sharing Consent and Share Credentials/updates/2023-08-11.md
Labels: Changes requested

#601 Week-6 Update
  docs/2023/Sunbird Lern/Integrate with non-Keycloak authentication system/updates/2023-08-11.md
Labels: Changes requested

#612 Week 6 + 7 Updates
  docs/2023/Template creation portal/Template creation portal/assets/homepage_ui_new.png
  docs/2023/Template creation portal/Template creation portal/assets/steppers.png
  docs/2023/Template creation portal/Template creation portal/updates/2023-08-04.md
  docs/2023/Template creation portal/Template creation portal/updates/2023-08-11.md
  docs/2023/Template creation portal/Template creation portal/updates/2023-08-18.md
Labels: build failure

#631 Update 2023-08-18.md - Week 7 report
  docs/2023/Farmstack/Dashboard Builder/updates/2023-08-18.md
Labels: build failure

#574 Week 6 updates
  docs/2023/Sunbird Lern/Keycloak Upgradation/updates/.2023-08-18.md.kate-swp
  docs/2023/Sunbird Lern/Keycloak Upgradation/updates/2023-07-07.md
  docs/2023/Sunbird Lern/Keycloak Upgradation/updates/2023-07-14.md
  docs/2023/Sunbird Lern/Keycloak Upgradation/updates/2023-07-21.md
  docs/2023/Sunbird Lern/Keycloak Upgradation/updates/2023-07-28.md
  docs/2023/Sunbird Lern/Keycloak Upgradation/updates/2023-08-04.md
  docs/2023/Sunbird Lern/Keycloak Upgradation/updates/2023-08-11.md
  docs/2023/Sunbird Lern/Keycloak Upgradation/updates/2023-08-18.md
Labels: Changes requested, build failure

#642 Week 6 Updates
  docs/2023/BeckN/Backn Smart Policy Infrastructure/index.md
  docs/2023/DevOps Pipeline/Build v2 of devops pipeline/updates/2023-08-11.md
  docs/2023/DevOps Pipeline/Build v2 of devops pipeline/updates/2023-08-18.md
Labels: build failure

#635 updated weekly milestones
  docs/2023/BeckN/Beckn in a box/updates/2023-08-11.md
  docs/2023/BeckN/Beckn in a box/updates/2023-08-18.md
Labels: build failure

#504 Adding week 5 blog for HCX Python SDK
  docs/2023/Health Claims Exchange/Python SDK/updates/2023-08-04.md
Labels: Changes requested

#554 Week 6, 7 milestones updated
  docs/2023/QuML/Enhanced Quml player for Enhanced Question types/updates/2023-08-11.md
  docs/2023/QuML/Enhanced Quml player for Enhanced Question types/updates/2023-08-18.md
  images/Screenshot 2023-08-11 201658.png
  images/Screenshot 2023-08-11 201718.png
  images/Screenshot 2023-08-11 201728.png
  images/Screenshot 2023-08-19 210111.png
  images/Screenshot 2023-08-19 210121.png
  images/Screenshot 2023-08-19 210146.png
  images/WhatsApp Image 2023-08-08 at 10.50.2.jpg
  images/WhatsApp Image 2023-08-08 at 10.50.28.jpg
  images/WhatsApp Image 2023-08-08 at 10.50.29.jpg
Labels: build failure

#608 Venu choudhary/cord
  docs/2023/CORD Network/IntegrationWithSunbirdRC/assets/keycloak-1.png
  docs/2023/CORD Network/IntegrationWithSunbirdRC/assets/keycloak-2.png
  docs/2023/CORD Network/IntegrationWithSunbirdRC/assets/week6-1.png
  docs/2023/CORD Network/IntegrationWithSunbirdRC/assets/week6-2.png
  docs/2023/CORD Network/IntegrationWithSunbirdRC/updates/2023-08-04.md
  docs/2023/CORD Network/IntegrationWithSunbirdRC/updates/2023-08-11.md
Labels: build failure

#617 Week 7 Milestones Update
  docs/2023/Sunbird ED/Search Widget or Discovery/updates/2023-08-18.md
Labels: build failure

#694 Week 7 update
  docs/2023/Unnati/Unnati PWA/updates/2023-08-18.md
Labels: Changes requested

#744 Added Week 8 updates
  docs/2023/cQube/cQubeChat/updates/2023-08-18.md
  docs/2023/cQube/cQubeChat/updates/2023-08-25.md
Labels: merge conflicts

#729 Update Week 7 & 8 milestones
  docs/2023/AI Tools/Dictionary Augmented Transformers/updates/2023-08-11.md
  docs/2023/AI Tools/Dictionary Augmented Transformers/updates/2023-08-18.md
  docs/2023/AI Tools/Dictionary Augmented Transformers/updates/2023-08-25.md
Labels: Changes requested

#322 Local
  docs/2023/Bahmni/Standalone Document Upload Module/updates/2023-07-07.md
  docs/2023/Bahmni/Standalone Document Upload Module/updates/2023-07-14.md
  docs/2023/Bahmni/Standalone Document Upload Module/updates/2023-07-21.md
  docs/2023/Bahmni/Standalone Document Upload Module/updates/2023-07-28.md
Labels: Changes requested

#734 Added week-8 contribution docs
  docs/2023/CARE/RedesignDoctorNotes/updates/2023-08-25.md
  docs/2023/CARE/RedesignDoctorNotes/updates/assets/CareRealtimeDoctorNotes.gif
Labels: Changes requested

#698 Week 7 and 8
  docs/2023/TrustBot and POSHpal/POSHpal/updates/2023-08-18.md
  docs/2023/TrustBot and POSHpal/POSHpal/updates/2023-08-25.md
Labels: Changes requested

#616 Week 6, 7 and 8 Milestones Updated
  docs/2023/Bahmni/Order Features/updates/2023-08-11.md
  docs/2023/Bahmni/Order Features/updates/2023-08-18.md
  docs/2023/Bahmni/Order Features/updates/2023-08-25.md
Labels: Changes requested

#699 week 6 update
  docs/2023/Sunbird ED/Bulk content creation/updates/2023-07-14.md
  docs/2023/Sunbird ED/Bulk content creation/updates/2023-07-21.md
  docs/2023/Sunbird ED/Bulk content creation/updates/2023-08-04.md
  docs/2023/Sunbird ED/Bulk content creation/updates/2023-08-11.md
  docs/2023/Sunbird ED/Bulk content creation/updates/2023-08-18.md
  docs/2023/Sunbird ED/Bulk content creation/updates/2023-08-25.md
Labels: Changes requested
